### ISSUE TITLE
Requests to /notify return 500 if error in processing even though we save the notification

### ISSUE THREAD

**Issue by simonpfry** [StemboltHQ/solidus-adyen#50]
Discovered as part of our issues with concurrency but not directly related, when there is an error processing a notification we save the notification but return 500 to Adyen. This makes Adyen repeat the notification, but because that's a duplicate we return 200, and don't attempt to process.

Not processing the duplicate is fine for us because we have a rake task which goes over unprocessed notifications, but might be for someone that doesn't have that.

So either we should recommend to have a job to clean up unprocessed notifications, and don't 500 on failure to process (so Adyen is happy and doesn't send again). Or we should 500 but actually process again on the duplicate notification sent afterwards (I assume we can rely on Adyen to always send a duplicate?)

**Comment by Dkendal** [comment]
Thanks for filing this, this is a known issue that I've never got around to writing up.

Cleaning up unprocessed notifications is probably a bad idea. Notifications should only 500 if an error occurs during processing.

For example: a refund notification is received and for whatever reason the refund can't be created.

An unprocessable notification like report_ready will be marked as unprocessed and will return a 200.

If we rescue the error so that we can return a 200 then all exceptional behavior in processing is going to be suppressed. The only way you'll ever know that something went wrong is by looking at the the notification history for a specific payment and see that something is unprocessed - but again you wouldn't know why.

In the other case, if we were to return a 500, and attempt to process when we receive the duplicate then we're never going to return anything other than a 500. We're going to report the same error over and over again because the system can't process the notification.
Due to the way that Rails does rendering it's impossible to raise an error and return anything other than a 500.

For this reason I think it's fine for us to raise the error as this does indicate that something has gone wrong and someone needs to look into it. It might not be ideal, but this is probably that closest we can get.

What I would really like to do in the event is report the error to some 3rd party like Honeybadger or Rollbar, but  because it's a gem I can't assume either are present. As a compromise how about supporting an extension point where the application can define how errors should be handled in processing?

**Comment by Dkendal** [comment]
Going to close this for now unless there is any other further concerns.
